
services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.9
    container_name: etcd
    environment:
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
    ports:
      - "2379:2379"

  patroni1:
    image: ghcr.io/zalando/spilo-16:3.3-p2
    container_name: patroni1
    environment:
      PATRONI_SCOPE: postgres_cluster
      PATRONI_NAME: patroni1
      PATRONI_ETCD3_HOSTS: "etcd:2379"
      PATRONI_ETCD_HOSTS: "etcd:2379"
      PATRONI_POSTGRESQL_DATA_DIR: /var/lib/postgresql/data
      PATRONI_REPLICATION_USERNAME: replicator
      PATRONI_REPLICATION_PASSWORD: replicator_password
      PATRONI_SUPERUSER_USERNAME: postgres
      # This doesnt seem to be used.. by looking at running container, seems to be using zalando as password.
      PATRONI_SUPERUSER_PASSWORD: postgres_password
    volumes:
      - patroni1_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    depends_on:
      - etcd
    networks:
      - postgres_network

  patroni2:
    image: ghcr.io/zalando/spilo-16:3.3-p2
    container_name: patroni2
    environment:
      PATRONI_SCOPE: postgres_cluster
      PATRONI_NAME: patroni2
      PATRONI_ETCD3_HOSTS: "etcd:2379"
      PATRONI_ETCD_HOSTS: "etcd:2379"
      PATRONI_POSTGRESQL_DATA_DIR: /var/lib/postgresql/data
      PATRONI_REPLICATION_USERNAME: replicator
      PATRONI_REPLICATION_PASSWORD: replicator_password
      PATRONI_SUPERUSER_USERNAME: postgres
      PATRONI_SUPERUSER_PASSWORD: postgres_password
    volumes:
      - patroni2_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    depends_on:
      - etcd
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

volumes:
  patroni1_data:
  patroni2_data:
